ROOT_PATH = '/'
AMINOACID_PATH = ROOT_PATH+'/aminoacids/atoms'
GROUP_DESCR = ROOT_PATH +'/aminoacids/data/atomic_groups.txt'
OUTPUT_PATH = ROOT_PATH + '/outputs'
PDBS_PATH = ROOT_PATH + '/pdbs/'
WATER_PATH = ROOT_PATH + '/pdbs/waters/'
NEW_WATER_PATH = ''
AMINO_PATH = ROOT_PATH + '/pdbs/aminos/'
TEMP_PATH = ROOT_PATH + '/pdbs/temp/'
USE_EVERY_FRAME = 1
VECTOR_START = 0.0
VECTOR_COUNT= 4
VECTOR_DIF = 0.02
MAX_PROC = 4
N_Z = 28
N_FI = 28
MULIT_MODEL_FILE = 'YES'
INDENT = 4
